name: Release

on:
  push:
    branches:
      - master
      - alpha
      - beta
    tags:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:

    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget

    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node
        
    - run: npm i && npx semantic-release
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        GH_TOKEN: ${{secrets.GH_TOKEN}}
